create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,name text not null,username text unique,age int,gender text,height numeric,weight numeric,fitness_level text not null default 'Beginner',activity_level text not null default 'Moderate',fitness_goal text not null default 'General Fitness',workout_preference text not null default 'Home',available_time int not null default 30,workout_days int not null default 3,preferred_workout_type text not null default 'Full Body',equipment text not null default 'None',food_preference text not null default 'Non-Vegetarian',allergies text,dietary_preferences text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.workouts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,workout_name text not null,date date not null,duration int not null default 0,completed boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.workout_exercises(id uuid primary key default gen_random_uuid(),workout_id uuid not null references public.workouts(id) on delete cascade,exercise_name text not null,sets int not null,reps int not null,weight numeric not null default 0,duration int not null default 0,rest int not null default 60,completed boolean not null default false);
create table if not exists public.nutrition(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,date date not null,meal_type text not null,meal_name text not null,calories numeric,protein numeric,carbohydrates numeric,fats numeric,completed boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.progress(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,date date not null,weight numeric,steps int,calories numeric,workout_duration int,created_at timestamptz not null default now());
create index if not exists workouts_user_date on public.workouts(user_id,date desc);create index if not exists progress_user_date on public.progress(user_id,date desc);

alter table public.profiles enable row level security;alter table public.workouts enable row level security;alter table public.workout_exercises enable row level security;alter table public.nutrition enable row level security;alter table public.progress enable row level security;
create policy profiles_own on public.profiles for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy workouts_own on public.workouts for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy workout_exercises_own on public.workout_exercises for all using(exists(select 1 from public.workouts w where w.id=workout_id and w.user_id=auth.uid())) with check(exists(select 1 from public.workouts w where w.id=workout_id and w.user_id=auth.uid()));
create policy nutrition_own on public.nutrition for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy progress_own on public.progress for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists profiles_updated_at on public.profiles;create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
