import {NextRequest,NextResponse} from 'next/server';
import {createServerClient} from '@supabase/ssr';
import {createClient} from '@supabase/supabase-js';
import {z} from 'zod';
const workoutSchema=z.object({goal:z.string().optional(),duration:z.coerce.number().min(5).max(180),fitnessLevel:z.string().optional(),location:z.string().optional(),equipment:z.string().optional(),muscleGroup:z.string().optional(),workoutType:z.string().optional()});
const nutritionSchema=z.object({calories:z.coerce.number().min(800).max(8000),preference:z.string().optional(),allergies:z.string().optional()});
const chatSchema=z.object({message:z.string().min(1).max(4000)});
async function auth(req:NextRequest){const s=createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{cookies:{getAll:()=>req.cookies.getAll(),setAll:()=>{}}});return {s,user:(await s.auth.getUser()).data.user};}
async function ai(prompt:string){const primary=(process.env.AI_PROVIDER||'gemini').toLowerCase();const gem=async()=>{if(!process.env.GEMINI_API_KEY)throw 0;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}]}),signal:AbortSignal.timeout(25000)});if(!r.ok)throw 0;const j=await r.json();return j.candidates?.[0]?.content?.parts?.map((p:any)=>p.text).join('')||''};const open=async()=>{if(!process.env.OPENAI_API_KEY)throw 0;const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:'gpt-4o-mini',messages:[{role:'system',content:'You are a safe fitness and nutrition wellness assistant.'},{role:'user',content:prompt}],temperature:.4}),signal:AbortSignal.timeout(25000)});if(!r.ok)throw 0;return (await r.json()).choices?.[0]?.message?.content||''};try{return primary==='openai'?await open():await gem()}catch{try{return primary==='openai'?await gem():await open()}catch{return null}}}
const parse=(s:string)=>{try{return JSON.parse(s.replace(/```json|```/g,'').trim())}catch{return null}};
const fallbackWorkout=(x:any)=>({workoutName:`${x.duration}-Minute ${x.goal||'Full Body'} Workout`,difficulty:x.fitnessLevel||'Beginner',exercises:(x.fitnessLevel==='Beginner'?['Bodyweight Squat','Push-up','Glute Bridge','Reverse Lunge','Plank']:['Goblet Squat','Dumbbell Row','Dumbbell Shoulder Press','Reverse Lunge','Plank']).map((n:string,i:number)=>({exerciseName:n,muscleGroup:i<2?'Legs':i===2?'Upper Body':'Core',sets:3,reps:n==='Plank'?null:(x.fitnessLevel==='Beginner'?10:12),duration:n==='Plank'?30:null,restTime:60,instructions:'Use controlled movement and stop if you feel sharp pain.'}))});
const fallbackNutrition=(x:any)=>({title:'Balanced Daily Plan',meals:[{mealType:'Breakfast',mealName:'Oats, fruit and yogurt',calories:400,protein:20,carbohydrates:55,fats:12},{mealType:'Lunch',mealName:'Rice, lentils and vegetables',calories:550,protein:30,carbohydrates:70,fats:15},{mealType:'Dinner',mealName:'Protein, grains and vegetables',calories:500,protein:30,carbohydrates:45,fats:18},{mealType:'Snack',mealName:'Fruit and yogurt',calories:200,protein:10,carbohydrates:28,fats:5}]});
export async function POST(req:NextRequest,{params}:{params:Promise<{route:string[]}>}){const {route}=await params;const path=route.join('/');
 if(path==='auth/username'){try{const b=z.object({username:z.string().min(3),password:z.string().min(1)}).parse(await req.json());const a=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{autoRefreshToken:false,persistSession:false}});const {data:p}=await a.from('profiles').select('user_id').eq('username',b.username.toLowerCase()).maybeSingle();if(!p)return NextResponse.json({error:'Invalid username or password'},{status:401});const {data:u}=await a.auth.admin.getUserById(p.user_id);return u.user?.email?NextResponse.json({email:u.user.email}):NextResponse.json({error:'Invalid username or password'},{status:401})}catch{return NextResponse.json({error:'Invalid username or password'},{status:401})}}
 const {s,user}=await auth(req);if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await req.json();
 if(path==='ai/workout'){const x=workoutSchema.parse(body);const text=await ai(`Return JSON only: workoutName,difficulty,exercises[]. Each exercise: exerciseName,muscleGroup,sets,reps,duration,restTime,instructions. Create a safe ${x.duration}-minute workout using ${JSON.stringify(x)}. Avoid medical claims.`);const data=text?parse(text):null;return NextResponse.json({data:data||fallbackWorkout(x),fallback:!data})}
 if(path==='ai/nutrition'){const x=nutritionSchema.parse(body);const text=await ai(`Return JSON only with title and meals[]. Each meal: mealType,mealName,calories,protein,carbohydrates,fats. Give general wellness guidance for ${JSON.stringify(x)} and respect allergies/preferences.`);const data=text?parse(text):null;return NextResponse.json({data:data||fallbackNutrition(x),fallback:!data})}
 if(path==='ai/chat'){const x=chatSchema.parse(body);const profile=(await s.from('profiles').select('name,age,height,weight,fitness_level,activity_level,fitness_goal,workout_preference,food_preference,allergies').eq('user_id',user.id).single()).data;const text=await ai(`You are FitAI Coach. Profile: ${JSON.stringify(profile)}. User: ${x.message}. Give concise safe wellness guidance. Do not diagnose. For injuries, severe pain, medical conditions or medication questions, recommend a qualified healthcare professional. Avoid extreme calorie restriction or dangerous workouts.`);return NextResponse.json({answer:text||'AI service is temporarily unavailable. Please try again, or use the basic recommendation tools.',fallback:!text})}
 if(path==='admin/stats'){const {data:role}=await s.from('admin_roles').select('role').eq('user_id',user.id).maybeSingle();if(!role)return NextResponse.json({error:'Forbidden'},{status:403});const a=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{autoRefreshToken:false,persistSession:false}});const cs=await Promise.all(['profiles','workouts','nutrition','ai_plans'].map(t=>a.from(t).select('*',{count:'exact',head:true})));return NextResponse.json({users:cs[0].count||0,workouts:cs[1].count||0,nutritionLogs:cs[2].count||0,aiPlans:cs[3].count||0})}
 return NextResponse.json({error:'Unknown endpoint'},{status:404})}catch(e){return NextResponse.json({error:e instanceof z.ZodError?'Invalid input':'Request failed'},{status:e instanceof z.ZodError?400:500})}}
